package com.ragapi.entity;

public enum LegalContractFormType {
    CHEMICAL_IMPORT_CONSULTING,
    CHEMICAL_EXPORT_CONSULTING,
    CHEMICAL_STORAGE_COMPLIANCE,
    CHEMICAL_PRODUCTION_LICENSE,
    CHEMICAL_SAFETY_AUDIT,
    GENERAL_LEGAL_CONSULTING
}
